name: Grid Test
favicon: null
layout_spectrum: 0.9987747126724571
typography_spectrum: 0.6742032698821276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#85111c'
    - '#808080'
    - '#00ffff'
    - '#050806'
  brandStrength: 0.75
  lightness: 0.8658674471080303
  saturation: 0.20201954408548772
  rhythmicContrast: 0.614510249812156
purpose: []
